# Generated by Django 4.2.3 on 2023-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='memo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
